name: Simone

on: [push]

jobs:
  Wizarding:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: vandijkstef/action-noticely@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}